# This is a basic workflow to help you get started with Actions

name: Auto fork

# Controls when the workflow will run

on: 
  schedule:
    - cron: "15 14 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Fetch upstream Action
        # You may pin to the exact commit or the version.
        # uses: 135e2/sync-upstream-repo@f12f0aa22ad51a1a2677f638da364c4e5525adb0
        uses: 135e2/sync-upstream-repo@v0.1.5
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/yangshun/tech-interview-handbook.git
          # repo branch to fetch
          upstream_branch: master
          # local repo branch
          local_branch: master
          # github push token
          github_token: ${{ secrets.GITHUB_TOKEN }}
